In [1]:
import numpy as np

In [3]:
a=np.array([[1,2],[3,4]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
a[0]

array([1, 2])

In [6]:
a[0,1]

2

In [7]:
a[0][1]

2

In [8]:
a[0,1:3]

array([2])

In [9]:
a[-1,-1]

4

In [10]:
a[::-1]

array([[3, 4],
       [1, 2]])

In [12]:
a=np.array(range(20)).reshape(4,5)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
a[2,2]

12

In [17]:
a[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [18]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
a>5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
boolind=a>5

In [21]:
a[boolind]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
b=np.array([[1,2],[3,4]])

In [24]:
b

array([[1, 2],
       [3, 4]])

In [25]:
c=np.array([[4,5]])

In [28]:
np.concatenate((b,c))

array([[1, 2],
       [3, 4],
       [4, 5]])

In [29]:
d=np.array([[4],[5]])

In [30]:
d

array([[4],
       [5]])

In [31]:
np.concatenate((d,b),axis=1)

array([[4, 1, 2],
       [5, 3, 4]])

In [32]:
np.concatenate((b,c), axis=None)

array([1, 2, 3, 4, 4, 5])

In [34]:
np.hstack((b,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [35]:
a=[1,2,3,4]
b=[4,4,5,6]

In [36]:
np.hstack((a,b))

array([1, 2, 3, 4, 4, 4, 5, 6])

In [37]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [4, 4, 5, 6]])