In [1]:
import numpy as np

In [9]:
a=np.array([[1,2,4],[3,4,5]], dtype='int64')

In [10]:
a

array([[1, 2, 4],
       [3, 4, 5]], dtype=int64)

In [11]:
a.dtype

dtype('int64')

In [12]:
b=a

In [13]:
b

array([[1, 2, 4],
       [3, 4, 5]], dtype=int64)

In [14]:
a[0]=43

In [15]:
b

array([[43, 43, 43],
       [ 3,  4,  5]], dtype=int64)

In [16]:
a[0]=34

In [18]:

b

array([[34, 34, 34],
       [ 3,  4,  5]], dtype=int64)

In [19]:
a

array([[34, 34, 34],
       [ 3,  4,  5]], dtype=int64)

In [20]:
b=a.copy()

In [21]:
b[0]=23

In [22]:
b

array([[23, 23, 23],
       [ 3,  4,  5]], dtype=int64)

In [23]:
a

array([[34, 34, 34],
       [ 3,  4,  5]], dtype=int64)

In [24]:
a=np.zeros((2,3))

In [25]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.full((3,4), 5.6)

array([[5.6, 5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6, 5.6],
       [5.6, 5.6, 5.6, 5.6]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [36]:
np.random.random((3,2))

array([[0.25419358, 0.01100171],
       [0.84026728, 0.31108009],
       [0.36893723, 0.44977575]])

In [38]:
np.random.randn(10)

array([-0.37652147, -1.10337181, -1.55888094, -1.6108942 ,  1.03650215,
        1.06825102, -0.58688589,  0.62344692,  0.30444667, -1.86993464])

In [39]:
a.mean()

0.0

In [40]:
a=np.random.randn(100)

In [41]:
a.mean()

-0.03566603095652125

In [42]:
a.var()

1.1226385166574504

In [44]:
a=np.random.randint(10, size=(3,3))

In [45]:
a

array([[0, 4, 8],
       [1, 1, 4],
       [9, 1, 6]])

In [46]:
a=np.random.choice(5, size=10)

In [47]:
a

array([4, 0, 0, 2, 0, 4, 0, 0, 0, 2])

In [48]:
a=np.array([[1,2],[3,4]])

In [50]:
eigenvalue,eigenvector=np.linalg.eig(a)

In [51]:
eigenvalue, eigenvector

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [52]:
eigenvalue

array([-0.37228132,  5.37228132])

In [53]:
eigenvector

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [54]:
b=eigenvector[:,0]* eigenvalue[0]

In [55]:
b

array([ 0.30697009, -0.21062466])

In [58]:
c=a@eigenvector[:,0]

In [59]:
c

array([ 0.30697009, -0.21062466])

In [60]:
b==c

array([ True, False])

In [61]:
np.allclose(b,c)

True

In [64]:
a=np.array([[1,1],[1.5,4.0]])
b=np.array([2200,5050])

In [65]:
np.linalg.inv(a).dot(b)

array([1500.,  700.])

In [66]:
a

array([[1. , 1. ],
       [1.5, 4. ]])

In [67]:
np.linalg.inv(a)

array([[ 1.6, -0.4],
       [-0.6,  0.4]])

In [68]:
np.linalg.solve(a,b)

array([1500.,  700.])

In [69]:
a=np.array([[1,1,3],[2,3,6],[6,5,3]])
b=np.array([1300,1400,1800])

In [70]:
np.linalg.inv(a).dot(b)

array([ 1060., -1200.,   480.])