In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.5


In [3]:
a=np.array([1,2,3
           ])

In [5]:
a

array([1, 2, 3])

In [6]:
l=[1,2,3]

In [7]:
b=np.array(l)

In [8]:
b

array([1, 2, 3])

In [9]:
c=[[1,2,3],[3,4,5]]

In [14]:
d=np.array(c, dtype='int64')

In [15]:
d.dtype

dtype('int64')

In [16]:
d.shape

(2, 3)

In [20]:
d.astype(float)

array([[1., 2., 3.],
       [3., 4., 5.]])

In [21]:
d.dtype

dtype('int64')

In [22]:
d.size

6

In [24]:
d.ndim

2

In [25]:
d.itemsize

8

In [26]:
a[0]

1

In [27]:
a[0]=10

In [28]:
a

array([10,  2,  3])

In [29]:
l=[1,2,3]
a=np.array(l)

In [30]:
l

[1, 2, 3]

In [31]:
a

array([1, 2, 3])

In [32]:
l.append(4)

In [33]:
l

[1, 2, 3, 4]

In [34]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [35]:
l=l+[4]

In [36]:
l

[1, 2, 3, 4, 4]

In [40]:
a=a+np.array([4])

In [38]:
a

array([5, 6, 7])

In [41]:
l=l*2

In [42]:
l

[1, 2, 3, 4, 4, 1, 2, 3, 4, 4]

In [43]:
a=a*2

In [44]:
a

array([18, 20, 22])

In [45]:
a

array([18, 20, 22])

In [46]:
l=[1,2,3]
a=np.array(l)

In [49]:
l

[1, 2, 3]

In [48]:
a

array([1, 2, 3])

In [50]:
l=l+[4]

In [51]:
a=a+np.array([4])

In [52]:
l

[1, 2, 3, 4]

In [53]:
a

array([5, 6, 7])

In [54]:
l=l*2
a=a*2

In [55]:
l

[1, 2, 3, 4, 1, 2, 3, 4]

In [56]:
a

array([10, 12, 14])

In [57]:
np.sqrt(a)

array([3.16227766, 3.46410162, 3.74165739])

In [58]:
np.log(a)

array([2.30258509, 2.48490665, 2.63905733])

In [59]:
l1=[1,2,3]
l2=[4,5,6]

In [60]:
a=np.array(l1)
b=np.array(l2)

In [61]:
a.dot(b)

32

In [63]:
sum=(a*b).sum()

In [64]:
sum

32

In [65]:
np.append(a,2)

array([1, 2, 3, 2])

In [66]:
np.insert(a,2,8)

array([1, 2, 8, 3])

In [67]:
#two dimensional array

In [68]:
a=np.array([[1,2,3],[2,4,6]])

In [69]:
a.shape

(2, 3)

In [71]:
a.reshape(3,2)

array([[1, 2],
       [3, 2],
       [4, 6]])

In [72]:
a

array([[1, 2, 3],
       [2, 4, 6]])

In [73]:
a=np.array([[1,2],[3,4]])

In [74]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [75]:
np.linalg.det(a)

-2.0000000000000004

In [77]:
c=np.diag(a)

In [78]:
c

array([1, 4])

In [79]:
np.diag(c)

array([[1, 0],
       [0, 4]])