In [1]:
#broadcasting


In [3]:
import numpy as np
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a+3

array([4, 5, 6, 7])

In [6]:
x=np.ones((3,4))
y=np.ones((3,1))

In [7]:
x+y

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [12]:
x=np.ones((3,4))
y=np.ones((1,4))

In [13]:
x+y

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [14]:
x,y=np.ogrid[1:10, 1:5]

In [15]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
y

array([[1, 2, 3, 4]])

In [17]:
x+1j*y

array([[1.+1.j, 1.+2.j, 1.+3.j, 1.+4.j],
       [2.+1.j, 2.+2.j, 2.+3.j, 2.+4.j],
       [3.+1.j, 3.+2.j, 3.+3.j, 3.+4.j],
       [4.+1.j, 4.+2.j, 4.+3.j, 4.+4.j],
       [5.+1.j, 5.+2.j, 5.+3.j, 5.+4.j],
       [6.+1.j, 6.+2.j, 6.+3.j, 6.+4.j],
       [7.+1.j, 7.+2.j, 7.+3.j, 7.+4.j],
       [8.+1.j, 8.+2.j, 8.+3.j, 8.+4.j],
       [9.+1.j, 9.+2.j, 9.+3.j, 9.+4.j]])

In [18]:
def grid_old_way():
    x,y=np.mgrid[1:100, 1:100]
    return x_1j*y

In [19]:
def grid_new_way():
    x,y=np.ogrid[1:100, 1:100]
    return x_1j*y

In [20]:
import timeit

In [21]:
timeit grid_new_way()

SyntaxError: invalid syntax (<ipython-input-21-18e8cd80cb08>, line 1)

In [22]:
x=np.zeros((3,5))
y=np.zeros(8)

In [23]:
(x[..., None]+y).shape

(3, 5, 8)

In [24]:
book=np.arange(1000).reshape(100,10)

In [25]:
match=np.array([np.arange])

In [26]:
x=np.arange(9).reshape((3,3))

In [27]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
# slicing and scalars

In [30]:
x[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [33]:
x[:,[0,1,2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
np.array([x[:,0],x[:,1],x[:,2]])

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [35]:
x=np.random.random((15,12,16,3))

In [36]:
index_one=np.array([[0,1],[2,3],[4,5]])
index_one.shape

(3, 2)

In [37]:
index_two=np.array([[0,1]])
index_two.shape

(1, 2)

In [38]:
ni,nj,nk=(10, 15, 20)

In [39]:
cube=np.empty((ni,nj, nk), dtype=int)

In [40]:
cube[:,:,:]=np.arange(nk)[np.newaxis, np.newaxis, :]

In [41]:
x=np.arange(20).reshape([4,5])

In [42]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
x.strides

(20, 4)

In [44]:
np.int32().itemsize

4

In [45]:
import numpy as np

In [46]:
a=np.array([[1,2],[3,4]])

In [47]:
b=np.array([[5,6],[7,8]])

In [48]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
c=[5,6]

In [53]:
np.column_stack((a,c))

array([[1, 2, 5],
       [3, 4, 6]])

In [54]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
np.hsplit(a,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [57]:
np.vsplit(a,2)

[array([[1, 2]]), array([[3, 4]])]

In [58]:
import numpy as np

In [59]:
a=np.array([1,2,3])

In [60]:
b=2.0


In [61]:
print(a*b)

[2. 4. 6.]


In [62]:
c=[2.0,2.0,2.0]

In [63]:
print(a*c)

[2. 4. 6.]


In [64]:
A=np.array([[6,1,1],
           [4,-2,5],
           [2,8,7]])

In [65]:
np.linalg.matrix_rank(A)

3

In [67]:
np.linalg.matrix_power(A,0)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [68]:
np.trace(A)

11

In [69]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [70]:
np.linalg.matrix_power(A,3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [71]:
a=np.array([[1,2],[3,4]])
b=np.array([8,18])

In [72]:
np.linalg.solve(a,b)

array([2., 3.])

In [73]:
x=np.array([[1,2],[3,4],[5,6]])

In [75]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
x[[0,1],[1,0]]

array([2, 3])

In [80]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [81]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [82]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
