In [1]:
import numpy as np

In [2]:
a=np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype.name

'int32'

In [10]:
a.dtype

dtype('int32')

In [11]:
b=[(1,2,3),(3,4,5)]

In [12]:
c=np.array(b)

In [13]:
c

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
c=np.array([[1,2,3],[3,4,5]],dtype=complex)

In [15]:
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.arange(1,10,4)

array([1, 5, 9])

In [21]:
range(1,10,1)

range(1, 10)

In [22]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [23]:
from numpy import pi

In [24]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
x=np.linspace(0,2*pi,100)

In [26]:
np.sin(x)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [27]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [28]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [31]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [33]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [34]:
a=np.array([20,30,40,50])

In [35]:
b=np.arange(4)

In [36]:
c=a-b

In [37]:
c

array([20, 29, 38, 47])

In [38]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [39]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [40]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [41]:
a<35

array([ True,  True, False, False])

In [42]:
A=np.array([[1,1],[0,1]])

In [43]:
B=np.array([[2,0],[3,4]])

In [44]:
A*B

array([[2, 0],
       [0, 4]])

In [45]:
A@B

array([[5, 4],
       [3, 4]])

In [46]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [47]:
rg=np.random.default_rng(1)

In [48]:
a=np.ones((2,3),dtype=int)

In [49]:
b=rg.random((2,3))

In [50]:
a*=3

In [51]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [52]:
a=np.ones(3, dtype=np.int32)
b=np.linspace(0,pi,3)

In [53]:
b.dtype.name

'float64'

In [54]:
a

array([1, 1, 1])

In [55]:
b

array([0.        , 1.57079633, 3.14159265])

In [56]:
c=a+b

In [57]:
c

array([1.        , 2.57079633, 4.14159265])

In [58]:
c.dtype.name

'float64'

In [59]:
d=np.exp(c*1j)

In [60]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [61]:
d.dtype.name

'complex128'

In [62]:
a=rg.random((2,3))

In [63]:
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [64]:
a.sum()

3.1057109529998157

In [65]:
a.min()

0.027559113243068367

In [66]:
a.max()

0.8277025938204418

In [67]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
b=np.arange(12).reshape((3,4))

In [69]:
b.sum()

66

In [71]:
b.min(axis=1)

array([0, 4, 8])

In [72]:
b.max(axis=1)

array([ 3,  7, 11])

In [73]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [74]:
b=np.arange(3)

In [75]:
b

array([0, 1, 2])

In [76]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [77]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [78]:
np.add(b,c)

array([1.        , 3.57079633, 6.14159265])

In [79]:
a=np.arange(14)

In [80]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [81]:
a**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169], dtype=int32)

In [82]:
a[3]

3

In [85]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05])

In [86]:
a=a**2

In [87]:
a[0]

0

In [88]:
a[4]

16

In [89]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169], dtype=int32)

In [90]:
a[4:9]

array([16, 25, 36, 49, 64], dtype=int32)

In [91]:
a[:6:2]

array([ 0,  4, 16], dtype=int32)

In [92]:
a[::2]

array([  0,   4,  16,  36,  64, 100, 144], dtype=int32)

In [93]:
a[::3]

array([  0,   9,  36,  81, 144], dtype=int32)

In [94]:
a[::-1]

array([169, 144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,   1,
         0], dtype=int32)

In [95]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169], dtype=int32)

In [96]:
a.reshape(2,7)

array([[  0,   1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144, 169]], dtype=int32)

In [97]:
a.flat

In [98]:
a.flat()

TypeError: 'numpy.flatiter' object is not callable

In [99]:
for i in a.flat:
    print(i)

0
1
4
9
16
25
36
49
64
81
100
121
144
169
