In [1]:
import numpy as np

In [2]:
a=np.array([8,8,7,7,0,4,2,5,2])

In [3]:
a

array([8, 8, 7, 7, 0, 4, 2, 5, 2])

In [4]:
index_get5=np.where(a>5)

In [5]:
index_get5

(array([0, 1, 2, 3], dtype=int64),)

In [6]:
a.take(index_get5)

array([[8, 8, 7, 7]])

In [7]:
np.set_printoptions(suppress=True)

In [10]:
path='https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'

In [11]:
data=np.genfromtxt(path, delimiter=',', skip_header=1,filling_values=-999, dtype='float')

In [12]:
data[:3]

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

In [13]:
data2=np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)

<ipython-input-13-af36daa80587>:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  data2=np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)


In [15]:
data2[:3]

array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', 'S38')])

In [16]:
np.savetxt('out.csv', data, delimiter=',')

In [17]:
a=np.random.randint(1,6, size=[8,4])

In [18]:
a

array([[1, 4, 4, 5],
       [3, 4, 4, 3],
       [1, 3, 2, 4],
       [2, 4, 1, 1],
       [5, 3, 1, 5],
       [5, 4, 2, 4],
       [5, 4, 5, 3],
       [1, 3, 2, 2]])

In [19]:
np.sort(a)

array([[1, 4, 4, 5],
       [3, 3, 4, 4],
       [1, 2, 3, 4],
       [1, 1, 2, 4],
       [1, 3, 5, 5],
       [2, 4, 4, 5],
       [3, 4, 5, 5],
       [1, 2, 2, 3]])

In [20]:
np.argwhere(a>2)

array([[0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 3],
       [3, 1],
       [4, 0],
       [4, 1],
       [4, 3],
       [5, 0],
       [5, 1],
       [5, 3],
       [6, 0],
       [6, 1],
       [6, 2],
       [6, 3],
       [7, 1]], dtype=int64)

In [21]:
a=np.arange(20)

In [23]:
a.argmax()

19

In [25]:
a.argsort()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [26]:
a=np.arange(20,1,-2)

In [27]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [28]:
a.argsort()

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [29]:
a=np.arange(10)

In [34]:
np.searchsorted(a,5)

5

In [35]:
a=np.arange(10,1,-1)

In [36]:
np.searchsorted(a,4)

0

In [37]:
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [38]:
np.searchsorted(a,5, side='right')

0

In [39]:
lst=range(1000)

In [40]:
probs=np.random.random(1000)

In [41]:
lst

range(0, 1000)

In [42]:
probs

array([0.54598453, 0.34613863, 0.13030576, 0.55950548, 0.98350631,
       0.09047797, 0.2806297 , 0.96867163, 0.9424962 , 0.41717197,
       0.98085899, 0.27340543, 0.22897206, 0.71068631, 0.31337671,
       0.24168994, 0.28894871, 0.47687706, 0.05197979, 0.14499901,
       0.34682321, 0.68094113, 0.1181373 , 0.10808129, 0.54691018,
       0.50517818, 0.93384963, 0.35061853, 0.35902187, 0.43614035,
       0.13680557, 0.06100907, 0.66289876, 0.76506838, 0.97207983,
       0.02683279, 0.19851504, 0.09543438, 0.20362538, 0.56548645,
       0.85831567, 0.47130301, 0.65157851, 0.18594518, 0.68018832,
       0.30805116, 0.27339482, 0.23271606, 0.00892656, 0.95697124,
       0.01911621, 0.17964528, 0.47180337, 0.04397614, 0.99359294,
       0.3299912 , 0.62114175, 0.99878679, 0.2546776 , 0.12339265,
       0.48075268, 0.0309005 , 0.86496433, 0.27459109, 0.53589206,
       0.63129103, 0.57712113, 0.4601482 , 0.87644327, 0.83137648,
       0.06476062, 0.28470018, 0.27307168, 0.55794738, 0.68668

In [43]:
x=np.arange(5)

In [44]:
x

array([0, 1, 2, 3, 4])

In [45]:
x_col=x[:, np.newaxis]

In [46]:
x_col.shape

(5, 1)

In [47]:
x_col

array([[0],
       [1],
       [2],
       [3],
       [4]])