In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4,5,6]

In [3]:
a=np.array(l1)

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
l1+2

TypeError: can only concatenate list (not "int") to list

In [ ]:
a+2

In [7]:
l1+[2]

[1, 2, 3, 4, 5, 6, 2]

In [8]:
a+[2]

array([3, 4, 5, 6, 7, 8])

In [9]:
li2=[[1,2,3],[4,5,6]]

In [10]:
a2=np.array(li2)

In [11]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
list(a2)

[array([1, 2, 3]), array([4, 5, 6])]

In [13]:
a2.tolist()

[[1, 2, 3], [4, 5, 6]]

In [14]:
a

array([1, 2, 3, 4, 5, 6])

In [15]:
a=np.arange(12)

In [16]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
a=a.reshape(3,4)

In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [20]:
a[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [21]:
a[::-1,::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [28]:
a.dtype(a.float64)

AttributeError: 'numpy.ndarray' object has no attribute 'float64'

In [30]:
np.amin(a, axis=0)

array([0, 1, 2, 3])

In [31]:
np.amin(a, axis=1)

array([0, 4, 8])

In [32]:
np.amax(a, axis=0)

array([ 8,  9, 10, 11])

In [33]:
np.amax(a, axis=1)

array([ 3,  7, 11])

In [34]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [35]:
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
a=np.arange(5)

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [44]:
np.arange(11,1,-1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [46]:
np.linspace(1,50,10,dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [47]:
np.set_printoptions(precision=2)

In [48]:
np.logspace(1,50,10, base=10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

In [49]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
a=[1,2,3]
print(np.tile(a,2))

[1 2 3 1 2 3]


In [54]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3])

In [55]:
np.random.rand((2,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [58]:
np.random.randn(2,4)

array([[-0.8 , -0.16,  0.45,  0.62],
       [-0.64,  0.42,  1.61,  0.65]])

In [59]:
np.random.rand(2,4)

array([[0.82, 0.74, 0.89, 0.43],
       [0.45, 0.01, 0.69, 0.24]])

In [60]:
np.random.randint(0,10, size=[2,2])

array([[9, 1],
       [5, 5]])

In [61]:
np.random.random()

0.9694752335788286

In [62]:
np.random.random(10)

array([0.16, 0.48, 0.25, 0.84, 0.36, 0.98, 0.71, 0.74, 0.83, 0.93])

In [63]:
np.random.choice(['a','e','i','o','u'], size=10)

array(['a', 'o', 'o', 'i', 'e', 'e', 'e', 'i', 'a', 'i'], dtype='<U1')

In [64]:
np.random.random(size=[2,2])

array([[0.33, 0.54],
       [0.94, 0.06]])

In [65]:
rn=np.random.RandomState(100)

In [66]:
print(rn.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


In [67]:
np.random.seed(100)

In [69]:
np.random.rand(2,2)

array([[0.54, 0.28],
       [0.42, 0.84]])

In [70]:
np.random.seed(100)