In [2]:
import numpy as np
import sys
from math import pi

In [5]:
rg=np.random.default_rng(1)
a=np.floor(10*rg.random((3,4)))

In [6]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [8]:
a.shape

(3, 4)

In [9]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.])

In [10]:
a.reshape(6,2)

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.],
       [5., 0.],
       [7., 5.]])

In [11]:
a

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [12]:
a.T

array([[5., 3., 5.],
       [9., 4., 0.],
       [1., 8., 7.],
       [9., 4., 5.]])

In [13]:
a.T.shape

(4, 3)

In [14]:
a.shape

(3, 4)

In [17]:
a.resize((2.6))

TypeError: 'float' object cannot be interpreted as an integer

In [18]:
a.reshape(3,-1)

array([[5., 9., 1., 9.],
       [3., 4., 8., 4.],
       [5., 0., 7., 5.]])

In [20]:
a=np.floor(10*rg.random((2,2)))

In [21]:
a

array([[1., 4.],
       [2., 2.]])

In [22]:
b=np.floor(10*rg.random((2,2)))

In [23]:
b

array([[7., 2.],
       [4., 9.]])

In [24]:
np.vstack((a,b))

array([[1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [25]:
np.hstack((a,b))

array([[1., 4., 7., 2.],
       [2., 2., 4., 9.]])

In [26]:
from numpy import newaxis

In [27]:
np.column_stack((a,b))

array([[1., 4., 7., 2.],
       [2., 2., 4., 9.]])

In [28]:
a=np.array([4,2])
b=np.array([3,8])

In [29]:
np.column_stack((a,b))

array([[4, 3],
       [2, 8]])

In [30]:
np.hstack((a,b))

array([4, 2, 3, 8])

In [31]:
np.vstack((a,b))

array([[4, 2],
       [3, 8]])

In [32]:
a=np.arange(12)**2

In [33]:
i=np.array([1,1,3,8,5])

In [34]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [35]:
palette=np.array([[0,0,0],
                 [255,0,0],
                  [0,255,0],
                  [0,0,255],
                  [255,255,255]])

In [36]:
image=np.array([[0,1,2,0],
               [0,3,4,0]])

In [37]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [38]:
a=np.arange(12).reshape(3,4)

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
i=np.array([[0,1],
           [1,2]])

In [41]:
j=np.array([[2,1],
           [3,3]])

In [42]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [43]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [44]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [45]:
l=(i,j)

In [46]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [47]:
s=np.array([i,j])

In [48]:
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [49]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [50]:
time=np.linspace(20,145,5)

In [51]:
data=np.sin(np.arange(20)).reshape(5,4)

In [52]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [53]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [54]:
ind=data.argmax(axis=0)

In [55]:
ind

array([2, 0, 3, 1], dtype=int64)